# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resources\ConnectionInputWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(260, 117)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font: 75 12pt \"Segoe UI\";\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #434F54;\n"
"    margin-top: 10px; /* Уменьшен отступ сверху */\n"
"    padding: 10px; /* Уменьшен padding */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px 0 3px;\n"
"    color: #A9B7C6;\n"
"}\n"
"\n"
"PlotWidget {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: #323232;\n"
"    gridline-color: #3c3f41;\n"
"    color: #A9B7C6;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #323232;\n"
"    color: #A9B7C6;\n"
"    padding: 5px;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #3c3f41;\n"
"    border-right: 1px solid #3c3f41;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #A9B7C6;\n"
"    background-color: #3C3F41;\n"
"    border: 1px solid #2B2B2B;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2B2B2B;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E4E4E;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #A9B7C6;\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #3C3F41;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #3C3F41;\n"
"    padding: 3px;\n"
"    min-width: 75px;\n"
"    selection-background-color: #4E4E4E;\n"
"    selection-color: #A9B7C6;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2B2B2B;\n"
"    border: 1px solid #3C3F41;\n"
"    color: #A9B7C6;\n"
"    selection-background-color: #4E4E4E;\n"
"    selection-color: #A9B7C6;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 20px;\n"
"    padding: 2px 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #4E4E4E;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #3C3F41;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #2B2B2B;\n"
"    border-bottom: 1px solid #3C3F41;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    color: #A9B7C6;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #3C3F41;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #3C3F41;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #3C3F41;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"}\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_port = QtWidgets.QLabel(Form)
        self.label_port.setObjectName("label_port")
        self.verticalLayout.addWidget(self.label_port)
        self.label_baudrate = QtWidgets.QLabel(Form)
        self.label_baudrate.setObjectName("label_baudrate")
        self.verticalLayout.addWidget(self.label_baudrate)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_port = QtWidgets.QComboBox(Form)
        self.comboBox_port.setObjectName("comboBox_port")
        self.verticalLayout_2.addWidget(self.comboBox_port)
        self.comboBox_baudrate = QtWidgets.QComboBox(Form)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_baudrate)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButton_connect = QtWidgets.QPushButton(Form)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_2.addWidget(self.pushButton_connect, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.comboBox_baudrate.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Подключение"))
        self.label_port.setText(_translate("Form", "Порт"))
        self.label_baudrate.setText(_translate("Form", "Скорость передачи"))
        self.comboBox_baudrate.setItemText(0, _translate("Form", "1200"))
        self.comboBox_baudrate.setItemText(1, _translate("Form", "2400"))
        self.comboBox_baudrate.setItemText(2, _translate("Form", "4800"))
        self.comboBox_baudrate.setItemText(3, _translate("Form", "9600"))
        self.comboBox_baudrate.setItemText(4, _translate("Form", "14400"))
        self.comboBox_baudrate.setItemText(5, _translate("Form", "19200"))
        self.comboBox_baudrate.setItemText(6, _translate("Form", "38400"))
        self.comboBox_baudrate.setItemText(7, _translate("Form", "57600"))
        self.comboBox_baudrate.setItemText(8, _translate("Form", "115200"))
        self.comboBox_baudrate.setItemText(9, _translate("Form", "128000"))
        self.comboBox_baudrate.setItemText(10, _translate("Form", "256000"))
        self.pushButton_connect.setText(_translate("Form", "Соеденить"))
