# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/DisplayOptionsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(256, 104)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #A9B7C6;\n"
"    background-color: #2B2B2B;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: center;\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"    font: 75 12pt \"Segoe UI\";\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #434F54;\n"
"    margin-top: 10px; /* Уменьшен отступ сверху */\n"
"    padding: 10px; /* Уменьшен padding */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px 0 3px;\n"
"    color: #A9B7C6;\n"
"}\n"
"\n"
"PlotWidget {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: #323232;\n"
"    gridline-color: #3c3f41;\n"
"    color: #A9B7C6;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #323232;\n"
"    color: #A9B7C6;\n"
"    padding: 5px;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #3c3f41;\n"
"    border-right: 1px solid #3c3f41;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #A9B7C6;\n"
"    background-color: #3C3F41;\n"
"    border: 1px solid #2B2B2B;\n"
"    padding: 10px;\n"
"        border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2B2B2B;\n"
"        border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E4E4E;\n"
"        border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #A9B7C6;\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #3C3F41;\n"
"        border-radius: 2px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #3C3F41;\n"
"    padding: 3px;\n"
"    min-width: 75px;\n"
"    selection-background-color: #4E4E4E;\n"
"    selection-color: #A9B7C6;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2B2B2B;\n"
"    border: 1px solid #3C3F41;\n"
"    color: #A9B7C6;\n"
"    selection-background-color: #4E4E4E;\n"
"    selection-color: #A9B7C6;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 20px;\n"
"    padding: 2px 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #4E4E4E;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #3C3F41;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #2B2B2B;\n"
"    border-bottom: 1px solid #3C3F41;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    color: #A9B7C6;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #3C3F41;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #3C3F41;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #3C3F41;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"}\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_check = QtWidgets.QLabel(Form)
        self.label_check.setObjectName("label_check")
        self.gridLayout_2.addWidget(self.label_check, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setEnabled(True)
        self.checkBox.setText("")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 1, 1, 1)
        self.label_count = QtWidgets.QLabel(Form)
        self.label_count.setObjectName("label_count")
        self.gridLayout_2.addWidget(self.label_count, 1, 0, 1, 1)
        self.lineEdit_count = QtWidgets.QLineEdit(Form)
        self.lineEdit_count.setEnabled(False)
        self.lineEdit_count.setObjectName("lineEdit_count")
        self.gridLayout_2.addWidget(self.lineEdit_count, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.pushButton_apply = QtWidgets.QPushButton(Form)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.gridLayout_3.addWidget(self.pushButton_apply, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_check.setText(_translate("Form", "Отображать все точки:"))
        self.label_count.setText(_translate("Form", "Сколько точек отображать:"))
        self.pushButton_apply.setText(_translate("Form", "Применить"))
