# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\resources\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 696)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("\n"
"    QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #2b2b2b;\n"
"    height: 15px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #2b2b2b;\n"
"    width: 15px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #51565d;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: #787878;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"    QMainWindow {\n"
"    background-color: #2b2b2b;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font: 75 12pt \"Segoe UI\";\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #434F54;\n"
"    margin-top: 10px; /* Уменьшен отступ сверху */\n"
"    padding: 10px; /* Уменьшен padding */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px 0 3px;\n"
"    color: #A9B7C6;\n"
"}\n"
"\n"
"PlotWidget {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: #323232;\n"
"    gridline-color: #3c3f41;\n"
"    color: #A9B7C6;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #323232;\n"
"    color: #A9B7C6;\n"
"    padding: 5px;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid #3c3f41;\n"
"    border-right: 1px solid #3c3f41;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #A9B7C6;\n"
"    background-color: #3C3F41;\n"
"    border: 1px solid #2B2B2B;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2B2B2B;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4E4E4E;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #A9B7C6;\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #3C3F41;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #2B2B2B;\n"
"    border-bottom: 1px solid #3C3F41;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    color: #A9B7C6;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #3C3F41;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"    border: 1px solid #3C3F41;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #3C3F41;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #2B2B2B;\n"
"    color: #A9B7C6;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.plot_widget = PlotWidget(self.groupBox_2)
        self.plot_widget.setObjectName("plot_widget")
        self.gridLayout_15.addWidget(self.plot_widget, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tableWidget = CustomQTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(15)
        self.tableWidget.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout_13.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_11.addWidget(self.lineEdit_3, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_14.addWidget(self.groupBox_9, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_14.addWidget(self.pushButton, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 103))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_time = QtWidgets.QLabel(self.groupBox_3)
        self.label_time.setObjectName("label_time")
        self.verticalLayout.addWidget(self.label_time)
        self.label_amperage = QtWidgets.QLabel(self.groupBox_3)
        self.label_amperage.setObjectName("label_amperage")
        self.verticalLayout.addWidget(self.label_amperage)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_time_out = QtWidgets.QLabel(self.groupBox_3)
        self.label_time_out.setObjectName("label_time_out")
        self.verticalLayout_5.addWidget(self.label_time_out)
        self.label_amperage_out = QtWidgets.QLabel(self.groupBox_3)
        self.label_amperage_out.setObjectName("label_amperage_out")
        self.verticalLayout_5.addWidget(self.label_amperage_out)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_14)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BMS Hub"))
        self.groupBox_2.setTitle(_translate("MainWindow", "График"))
        self.groupBox.setTitle(_translate("MainWindow", "Ячейки"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Порог"))
        self.pushButton.setText(_translate("MainWindow", "НАЧАТЬ ЦИКЛ"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Общее"))
        self.label_time.setText(_translate("MainWindow", "Время:"))
        self.label_amperage.setText(_translate("MainWindow", "Ток:"))
        self.label_time_out.setText(_translate("MainWindow", "_"))
        self.label_amperage_out.setText(_translate("MainWindow", "_"))
        self.menu.setTitle(_translate("MainWindow", "Данные"))
        self.action.setText(_translate("MainWindow", "Выгрузить данные с устройства"))
        self.action_2.setText(_translate("MainWindow", "Экспорт"))
        self.action_3.setText(_translate("MainWindow", "Иморт"))
        self.action_4.setText(_translate("MainWindow", "Установить соединение"))
        self.action_5.setText(_translate("MainWindow", "Очистить файл"))
from pyqtgraph import PlotWidget
from widgets.custom_table_widget import CustomQTableWidget
